import Head from 'next/head'
import Link from 'next/link'
import StickyHomePage from '../components/StickyHomePage'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='header'>
        <div className='headerContainer'>
          <Link href="/">Home</Link>
          <Link href="/resume">Resume</Link>
        </div>
      </header>

      <main className={styles.main}>
        <StickyHomePage/>
      </main>
    </div>
  )
}
